const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const number=new Intl.NumberFormat('en-US',{maximumFractionDigits:4});
const expression=$('#expression'), result=$('#result');
let angleMode='deg', memory=Number(localStorage.getItem('cr-memory')||0), lastResult=0;
const devMode=$('#devMode'), gamesView=$('#gamesView'), lockButton=$('#lockButton');

function normalizeExpression(raw){
  let value=raw.trim().replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('π','PI').replaceAll('√','sqrt');
  value=value.replace(/(\d|\)|PI)\s*(?=PI|sin|cos|tan|ln|log|sqrt|\()/g,'$1*').replace(/\^/g,'**').replace(/(\d+(?:\.\d+)?)%/g,'($1/100)');
  if(!/^(?:[\d\s.+\-*/%(),]|\*\*|PI|E|sin|cos|tan|ln|log|sqrt|abs)*$/.test(value))throw Error('Unsupported expression');
  const trig=angleMode==='deg'?{sin:'((x)=>Math.sin(x*Math.PI/180))',cos:'((x)=>Math.cos(x*Math.PI/180))',tan:'((x)=>Math.tan(x*Math.PI/180))'}:{sin:'Math.sin',cos:'Math.cos',tan:'Math.tan'};
  return value.replace(/\bPI\b/g,'Math.PI').replace(/\bE\b/g,'Math.E').replace(/\bsin\b/g,trig.sin).replace(/\bcos\b/g,trig.cos).replace(/\btan\b/g,trig.tan).replace(/\bln\b/g,'Math.log').replace(/\blog\b/g,'Math.log10').replace(/\bsqrt\b/g,'Math.sqrt').replace(/\babs\b/g,'Math.abs');
}
function evaluate(showError=false){
  if(!expression.value.trim()){result.textContent='0';return 0}
  try{const value=Function('"use strict"; return ('+normalizeExpression(expression.value)+')')();if(!Number.isFinite(value))throw Error();lastResult=value;result.textContent=Number.isInteger(value)?number.format(value):Number(value.toPrecision(12)).toLocaleString('en-US',{maximumFractionDigits:10});return value}catch(e){if(showError)result.textContent='Check expression';return null}
}
$('#keypad').addEventListener('click',event=>{
  const key=event.target.closest('button');if(!key)return;const action=key.dataset.action;
  if(action==='clear'){expression.value='';result.textContent='0';lastResult=0}
  else if(action==='delete'){expression.value=expression.value.slice(0,-1);evaluate()}
  else if(action==='equals')evaluate(true);
  else if(action==='square'){expression.value=expression.value?'('+expression.value+')^2':'';evaluate()}
  else if(action==='memory-add'){memory+=evaluate()||0;localStorage.setItem('cr-memory',memory);updateMemory();showToast('Added to memory')}
  else if(action==='memory-recall'){expression.value+=String(memory);evaluate()}
  else if(action==='last-result'){expression.value+=String(lastResult);evaluate()}
  else if(action==='sign'){expression.value=expression.value?'-('+expression.value+')':'-';evaluate()}
  else{expression.value+=key.dataset.value||'';evaluate();checkDeveloperCode()}
  expression.focus();
});
expression.addEventListener('input',()=>{evaluate();checkDeveloperCode()});expression.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();evaluate(true)}if(event.key==='Escape'){expression.value='';result.textContent='0'}});
function updateMemory(){$('#memoryLabel').textContent='Memory: '+number.format(memory)}updateMemory();
['deg','rad'].forEach(mode=>$('#'+mode+'Mode').addEventListener('click',()=>{angleMode=mode;$('#degMode').classList.toggle('active',mode==='deg');$('#radMode').classList.toggle('active',mode==='rad');evaluate()}));

const field=(name,label,value,options={})=>{const prefix=options.prefix?`<span class="prefix">${options.prefix}</span>`:'',suffix=options.suffix?`<span class="suffix">${options.suffix}</span>`:'',classes=`${options.prefix?'has-prefix':''} ${options.suffix?'has-suffix':''}`;return `<div class="field ${options.full?'full':''}"><label for="${name}">${label}</label><div class="input-wrap">${prefix}<input class="${classes}" id="${name}" name="${name}" type="${options.type||'number'}" value="${value}" ${options.step?`step="${options.step}"`:''} ${options.min!==undefined?`min="${options.min}"`:''} required>${suffix}</div></div>`};
const selectField=(name,label,options,full=false)=>`<div class="field ${full?'full':''}"><label for="${name}">${label}</label><select id="${name}" name="${name}">${options.map(o=>`<option value="${o[0]}">${o[1]}</option>`).join('')}</select></div>`;
const actionButton=(label='Calculate')=>`<button class="calculate-btn" type="submit">${label}</button>`;
const val=(form,name)=>Number(form.elements[name].value), detail=(label,value)=>`<div class="answer-row"><span>${label}</span><strong>${value}</strong></div>`;

const toolDefinitions={
  compound:{title:'Compound interest',description:'Project growth with compounding and regular deposits.',icon:'↗',form:()=>field('principal','Starting amount','10000',{prefix:'$',min:0})+field('rate','Annual interest rate','6',{suffix:'%',step:'0.01',min:0})+field('years','Time period','10',{suffix:'years',step:'0.5',min:0})+field('contribution','Monthly contribution','250',{prefix:'$',min:0})+selectField('frequency','Compound frequency',[['12','Monthly'],['4','Quarterly'],['2','Semiannually'],['1','Annually']])+actionButton('Calculate growth'),calculate(form){const p=val(form,'principal'),r=val(form,'rate')/100,years=val(form,'years'),monthly=val(form,'contribution'),n=val(form,'frequency');if(p<0||r<0||years<0||monthly<0)throw Error();const base=p*Math.pow(1+r/n,n*years),periods=n*years,payment=monthly*12/n,deposits=r===0?payment*periods:payment*((Math.pow(1+r/n,periods)-1)/(r/n)),total=base+deposits,contributed=p+monthly*12*years;return{value:money.format(total),details:detail('Total contributions',money.format(contributed))+detail('Interest earned',money.format(total-contributed))+detail('Growth',number.format(contributed?(total/contributed-1)*100:0)+'%')}}},
  simple:{title:'Simple interest',description:'Interest calculated only on the original principal.',icon:'$',form:()=>field('principal','Principal amount','5000',{prefix:'$',min:0})+field('rate','Annual interest rate','5',{suffix:'%',step:'0.01',min:0})+field('years','Time period','3',{suffix:'years',step:'0.25',min:0})+actionButton(),calculate(form){const p=val(form,'principal'),r=val(form,'rate')/100,t=val(form,'years');if(p<0||r<0||t<0)throw Error();const interest=p*r*t;return{value:money.format(p+interest),details:detail('Principal',money.format(p))+detail('Interest',money.format(interest))+detail('Effective return',number.format(r*t*100)+'%')}}},
  loan:{title:'Loan & mortgage',description:'Estimate payments for a fixed-rate amortizing loan.',icon:'⌂',form:()=>field('amount','Loan amount','300000',{prefix:'$',min:0})+field('rate','Annual interest rate','6.5',{suffix:'%',step:'0.01',min:0})+field('years','Loan term','30',{suffix:'years',min:1})+field('down','Down payment','0',{prefix:'$',min:0})+actionButton('Estimate payment'),calculate(form){const amount=val(form,'amount')-val(form,'down'),annual=val(form,'rate')/100,months=val(form,'years')*12,r=annual/12;if(amount<0||annual<0||months<=0)throw Error();const payment=r===0?amount/months:amount*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1),total=payment*months;return{value:money.format(payment)+'/mo',details:detail('Amount financed',money.format(amount))+detail('Total interest',money.format(total-amount))+detail('Total of payments',money.format(total)),note:'Estimate excludes property taxes, insurance, fees, and changing rates.'}}},
  savings:{title:'Savings goal',description:'Calculate the monthly savings needed to hit a target.',icon:'◎',form:()=>field('goal','Savings goal','25000',{prefix:'$',min:0})+field('current','Already saved','5000',{prefix:'$',min:0})+field('rate','Annual return','4',{suffix:'%',step:'0.01',min:0})+field('years','Time to goal','3',{suffix:'years',step:'0.25',min:.1})+actionButton('Build savings plan'),calculate(form){const goal=val(form,'goal'),current=val(form,'current'),annual=val(form,'rate')/100,months=val(form,'years')*12,r=annual/12;if(goal<0||current<0||annual<0||months<=0)throw Error();const futureCurrent=current*Math.pow(1+r,months),needed=Math.max(0,goal-futureCurrent),payment=r===0?needed/months:needed*r/(Math.pow(1+r,months)-1),deposits=payment*months;return{value:money.format(payment)+'/mo',details:detail('Starting savings at goal',money.format(futureCurrent))+detail('New contributions',money.format(deposits))+detail('Estimated earnings',money.format(Math.max(0,goal-current-deposits)))}}},
  percent:{title:'Percentage',description:'Solve common percentage questions instantly.',icon:'%',form:()=>selectField('mode','Calculation',[['of','What is X% of Y?'],['change','Percentage change'],['ratio','X is what percent of Y?']],true)+field('first','First value','20')+field('second','Second value','150')+actionButton(),calculate(form){const a=val(form,'first'),b=val(form,'second'),mode=form.elements.mode.value;let out,rows;if(mode==='of'){out=a/100*b;rows=detail(`${a}% of ${number.format(b)}`,number.format(out))}else if(mode==='change'){if(a===0)throw Error();out=(b-a)/Math.abs(a)*100;rows=detail('Starting value',number.format(a))+detail('Ending value',number.format(b))+detail('Direction',out>=0?'Increase':'Decrease')}else{if(b===0)throw Error();out=a/b*100;rows=detail('Part',number.format(a))+detail('Whole',number.format(b))}return{value:number.format(out)+(mode==='of'?'':'%'),details:rows}}},
  tip:{title:'Tip & split',description:'Split a bill fairly, including the tip.',icon:'÷',form:()=>field('bill','Bill amount','84.50',{prefix:'$',step:'0.01',min:0})+field('tip','Tip','20',{suffix:'%',step:'1',min:0})+field('people','Number of people','3',{min:1,step:'1'})+actionButton('Split bill'),calculate(form){const bill=val(form,'bill'),rate=val(form,'tip')/100,people=Math.floor(val(form,'people'));if(bill<0||rate<0||people<1)throw Error();const tip=bill*rate,total=bill+tip,each=total/people;return{value:money.format(each)+' each',details:detail('Tip amount',money.format(tip))+detail('Total bill',money.format(total))+detail('Party size',people+' people')}}},
  date:{title:'Date difference',description:'Measure the time between two calendar dates.',icon:'□',form:()=>field('start','Start date',new Date().toISOString().slice(0,10),{type:'date'})+field('end','End date',new Date(Date.now()+7*86400000).toISOString().slice(0,10),{type:'date'})+actionButton('Count days'),calculate(form){const start=new Date(form.elements.start.value+'T00:00:00Z'),end=new Date(form.elements.end.value+'T00:00:00Z');if(isNaN(start)||isNaN(end))throw Error();const days=Math.round(Math.abs(end-start)/86400000),weeks=Math.floor(days/7),remaining=days%7;return{value:number.format(days)+' days',details:detail('In weeks',number.format(days/7)+' weeks')+detail('Calendar span',weeks+' weeks, '+remaining+' days')+detail('Order',end>=start?'Forward in time':'Dates reversed')}}},
  convert:{title:'Unit converter',description:'Convert common measurements quickly and accurately.',icon:'⇄',form:()=>selectField('category','Measurement',[['length','Length'],['mass','Weight / mass'],['temperature','Temperature'],['area','Area'],['volume','Volume'],['speed','Speed']],true)+field('amount','Value','1',{step:'any'})+selectField('from','From',[['m','Meters']])+selectField('to','To',[['ft','Feet']])+actionButton('Convert'),onRender(form){const refresh=()=>populateUnits(form);form.elements.category.addEventListener('change',refresh);refresh()},calculate(form){const category=form.elements.category.value,amount=val(form,'amount'),from=form.elements.from.value,to=form.elements.to.value;if(!Number.isFinite(amount))throw Error();let out;if(category==='temperature')out=from==='c'?(to==='f'?amount*9/5+32:to==='k'?amount+273.15:amount):from==='f'?(to==='c'?(amount-32)*5/9:to==='k'?(amount-32)*5/9+273.15:amount):(to==='c'?amount-273.15:to==='f'?(amount-273.15)*9/5+32:amount);else{const factors=unitSets[category].factors;out=amount*factors[from]/factors[to]}const fromLabel=form.elements.from.selectedOptions[0].text,toLabel=form.elements.to.selectedOptions[0].text;return{value:number.format(out)+' '+toLabel,details:detail('Original',number.format(amount)+' '+fromLabel)+detail('Conversion factor',number.format(amount===0?0:out/amount))}}},
  bmi:{title:'BMI',description:'Estimate body mass index using metric or US units.',icon:'△',form:()=>selectField('system','Measurement system',[['us','US (inches, pounds)'],['metric','Metric (centimeters, kilograms)']],true)+field('height','Height','68',{suffix:'in',step:'0.1',min:1})+field('weight','Weight','160',{suffix:'lb',step:'0.1',min:1})+actionButton('Calculate BMI'),onRender(form){form.elements.system.addEventListener('change',()=>{const metric=form.elements.system.value==='metric';form.elements.height.value=metric?'173':'68';form.elements.weight.value=metric?'73':'160';form.elements.height.nextElementSibling.textContent=metric?'cm':'in';form.elements.weight.nextElementSibling.textContent=metric?'kg':'lb'})},calculate(form){const h=val(form,'height'),w=val(form,'weight'),metric=form.elements.system.value==='metric';if(h<=0||w<=0)throw Error();const bmi=metric?w/Math.pow(h/100,2):703*w/Math.pow(h,2),category=bmi<18.5?'Below standard range':bmi<25?'Standard range':bmi<30?'Above standard range':'High range';return{value:number.format(bmi),details:detail('Category',category)+detail('Standard reference','18.5 – 24.9'),note:'BMI is a general screening estimate, not a diagnosis or a substitute for medical guidance.'}}}
};

const unitSets={length:{units:[['m','Meters'],['km','Kilometers'],['cm','Centimeters'],['mm','Millimeters'],['ft','Feet'],['in','Inches'],['yd','Yards'],['mi','Miles']],factors:{m:1,km:1000,cm:.01,mm:.001,ft:.3048,in:.0254,yd:.9144,mi:1609.344}},mass:{units:[['kg','Kilograms'],['g','Grams'],['lb','Pounds'],['oz','Ounces'],['t','Metric tons']],factors:{kg:1,g:.001,lb:.45359237,oz:.028349523,t:1000}},temperature:{units:[['c','Celsius'],['f','Fahrenheit'],['k','Kelvin']],factors:{}},area:{units:[['sqm','Square meters'],['sqkm','Square kilometers'],['sqft','Square feet'],['sqyd','Square yards'],['acre','Acres'],['hectare','Hectares']],factors:{sqm:1,sqkm:1e6,sqft:.09290304,sqyd:.83612736,acre:4046.8564224,hectare:10000}},volume:{units:[['l','Liters'],['ml','Milliliters'],['gal','US gallons'],['qt','US quarts'],['cup','US cups'],['floz','Fluid ounces']],factors:{l:1,ml:.001,gal:3.785411784,qt:.946352946,cup:.2365882365,floz:.0295735296}},speed:{units:[['mps','Meters/second'],['kph','Kilometers/hour'],['mph','Miles/hour'],['knot','Knots']],factors:{mps:1,kph:.277777778,mph:.44704,knot:.514444444}}};
function populateUnits(form){const set=unitSets[form.elements.category.value],options=set.units.map(u=>`<option value="${u[0]}">${u[1]}</option>`).join('');form.elements.from.innerHTML=options;form.elements.to.innerHTML=options;form.elements.to.selectedIndex=Math.min(1,set.units.length-1)}
const panel=$('#toolPanel'),form=$('#toolForm');
function openTool(name){const tool=toolDefinitions[name];if(!tool)return;panel.hidden=false;$('#panelHeading').textContent=tool.title;$('#panelDescription').textContent=tool.description;$('#panelIcon').textContent=tool.icon;form.innerHTML=tool.form();$('#answerValue').textContent='—';$('#answerDetails').innerHTML=detail('Enter your details','Ready when you are');$('#answerNote').textContent='Results are estimates and are provided for general informational purposes.';form.dataset.tool=name;if(tool.onRender)tool.onRender(form);panel.scrollIntoView({behavior:'smooth',block:'start'})}
$$('.open-tool').forEach(btn=>btn.addEventListener('click',()=>openTool(btn.dataset.tool)));$('#closePanel').addEventListener('click',()=>panel.hidden=true);
form.addEventListener('submit',event=>{event.preventDefault();const tool=toolDefinitions[form.dataset.tool];try{const answer=tool.calculate(form);$('#answerValue').textContent=answer.value;$('#answerDetails').innerHTML=answer.details;$('#answerNote').textContent=answer.note||'Results are estimates and are provided for general informational purposes.'}catch(e){$('#answerValue').textContent='Check your entries';$('#answerDetails').innerHTML=detail('Status','Use valid values in every field')}});
$$('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const filter=btn.dataset.filter;$$('.tool-card').forEach(card=>card.classList.toggle('hidden',filter!=='all'&&!card.dataset.category.split(' ').includes(filter)))}));
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),1800)}
$('#year').textContent=new Date().getFullYear();

function grantGameAccess(){sessionStorage.setItem('gameAccess','unlocked');document.cookie='calc_ready=1; Path=/; Max-Age=3600; SameSite=Lax'}
function hasGameAccess(){return sessionStorage.getItem('gameAccess')==='unlocked'||document.cookie.split(';').some(part=>part.trim()==='calc_ready=1')}
function clearGameAccess(){sessionStorage.removeItem('gameAccess');document.cookie='calc_ready=; Path=/; Max-Age=0; SameSite=Lax'}
function checkDeveloperCode(){if(devMode.checked&&expression.value.replace(/\s/g,'').endsWith('0000'))openGames()}
function openGames(){grantGameAccess();document.body.classList.add('body-game-open');gamesView.classList.add('unlocked');expression.value='';result.textContent='0';window.scrollTo({top:0,behavior:'smooth'})}
function closeGames(){clearGameAccess();gamesView.classList.remove('unlocked');document.body.classList.remove('body-game-open');devMode.checked=false;expression.value='';result.textContent='0';window.scrollTo({top:0,behavior:'smooth'})}
devMode.addEventListener('change',()=>{if(devMode.checked)showToast('Developer mode ready');else showToast('Developer mode off')});
lockButton.addEventListener('click',closeGames);
if(hasGameAccess())openGames();
