const pageMoney=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const pageNumber=new Intl.NumberFormat('en-US',{maximumFractionDigits:4});
const byId=id=>document.getElementById(id);
const field=(name,label,value,options={})=>`<div class="field ${options.full?'full':''}"><label for="${name}">${label}</label><div class="input-wrap">${options.prefix?`<span class="prefix">${options.prefix}</span>`:''}<input class="${options.prefix?'has-prefix':''} ${options.suffix?'has-suffix':''}" id="${name}" name="${name}" type="${options.type||'number'}" value="${value}" ${options.step?`step="${options.step}"`:''} ${options.min!==undefined?`min="${options.min}"`:''} required>${options.suffix?`<span class="suffix">${options.suffix}</span>`:''}</div></div>`;
const selectField=(name,label,options,full=false)=>`<div class="field ${full?'full':''}"><label for="${name}">${label}</label><select id="${name}" name="${name}">${options.map(([value,text])=>`<option value="${value}">${text}</option>`).join('')}</select></div>`;
const button=label=>`<button class="calculate-btn" type="submit">${label}</button>`;
const value=(form,name)=>Number(form.elements[name].value);
const row=(label,result)=>`<div class="answer-row"><span>${label}</span><strong>${result}</strong></div>`;

const units={
  length:{items:[['m','Meters'],['km','Kilometers'],['cm','Centimeters'],['mm','Millimeters'],['ft','Feet'],['in','Inches'],['yd','Yards'],['mi','Miles']],factors:{m:1,km:1000,cm:.01,mm:.001,ft:.3048,in:.0254,yd:.9144,mi:1609.344}},
  mass:{items:[['kg','Kilograms'],['g','Grams'],['lb','Pounds'],['oz','Ounces'],['t','Metric tons']],factors:{kg:1,g:.001,lb:.45359237,oz:.028349523,t:1000}},
  temperature:{items:[['c','Celsius'],['f','Fahrenheit'],['k','Kelvin']],factors:{}},
  area:{items:[['sqm','Square meters'],['sqkm','Square kilometers'],['sqft','Square feet'],['sqyd','Square yards'],['acre','Acres'],['hectare','Hectares']],factors:{sqm:1,sqkm:1e6,sqft:.09290304,sqyd:.83612736,acre:4046.8564224,hectare:10000}},
  volume:{items:[['l','Liters'],['ml','Milliliters'],['gal','US gallons'],['qt','US quarts'],['cup','US cups'],['floz','Fluid ounces']],factors:{l:1,ml:.001,gal:3.785411784,qt:.946352946,cup:.2365882365,floz:.0295735296}},
  speed:{items:[['mps','Meters/second'],['kph','Kilometers/hour'],['mph','Miles/hour'],['knot','Knots']],factors:{mps:1,kph:.277777778,mph:.44704,knot:.514444444}}
};

const tools={
  compound:{form:()=>field('principal','Starting amount','10000',{prefix:'$',min:0})+field('rate','Annual interest rate','6',{suffix:'%',step:'0.01',min:0})+field('years','Time period','10',{suffix:'years',step:'0.5',min:0})+field('contribution','Monthly contribution','250',{prefix:'$',min:0})+selectField('frequency','Compound frequency',[['12','Monthly'],['4','Quarterly'],['2','Semiannually'],['1','Annually']])+button('Calculate growth'),calculate(form){const p=value(form,'principal'),r=value(form,'rate')/100,years=value(form,'years'),monthly=value(form,'contribution'),n=value(form,'frequency');if(p<0||r<0||years<0||monthly<0)throw Error();const periods=n*years,base=p*Math.pow(1+r/n,periods),payment=monthly*12/n,deposits=r===0?payment*periods:payment*(Math.pow(1+r/n,periods)-1)/(r/n),total=base+deposits,contributed=p+monthly*12*years;return[pageMoney.format(total),row('Total contributions',pageMoney.format(contributed))+row('Interest earned',pageMoney.format(total-contributed))+row('Growth',pageNumber.format(contributed?(total/contributed-1)*100:0)+'%')] }},
  simple:{form:()=>field('principal','Principal amount','5000',{prefix:'$',min:0})+field('rate','Annual interest rate','5',{suffix:'%',step:'0.01',min:0})+field('years','Time period','3',{suffix:'years',step:'0.25',min:0})+button('Calculate total'),calculate(form){const p=value(form,'principal'),r=value(form,'rate')/100,t=value(form,'years');if(p<0||r<0||t<0)throw Error();const interest=p*r*t;return[pageMoney.format(p+interest),row('Principal',pageMoney.format(p))+row('Interest',pageMoney.format(interest))+row('Effective return',pageNumber.format(r*t*100)+'%')] }},
  loan:{form:()=>field('amount','Loan amount','300000',{prefix:'$',min:0})+field('rate','Annual interest rate','6.5',{suffix:'%',step:'0.01',min:0})+field('years','Loan term','30',{suffix:'years',min:1})+field('down','Down payment','0',{prefix:'$',min:0})+button('Estimate payment'),calculate(form){const amount=value(form,'amount')-value(form,'down'),annual=value(form,'rate')/100,months=value(form,'years')*12,r=annual/12;if(amount<0||annual<0||months<=0)throw Error();const payment=r===0?amount/months:amount*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1),total=payment*months;return[pageMoney.format(payment)+'/mo',row('Amount financed',pageMoney.format(amount))+row('Total interest',pageMoney.format(total-amount))+row('Total of payments',pageMoney.format(total))] }},
  savings:{form:()=>field('goal','Savings goal','25000',{prefix:'$',min:0})+field('current','Already saved','5000',{prefix:'$',min:0})+field('rate','Annual return','4',{suffix:'%',step:'0.01',min:0})+field('years','Time to goal','3',{suffix:'years',step:'0.25',min:.1})+button('Build savings plan'),calculate(form){const goal=value(form,'goal'),current=value(form,'current'),annual=value(form,'rate')/100,months=value(form,'years')*12,r=annual/12;if(goal<0||current<0||annual<0||months<=0)throw Error();const future=current*Math.pow(1+r,months),needed=Math.max(0,goal-future),payment=r===0?needed/months:needed*r/(Math.pow(1+r,months)-1),deposits=payment*months;return[pageMoney.format(payment)+'/mo',row('Starting savings at goal',pageMoney.format(future))+row('New contributions',pageMoney.format(deposits))+row('Estimated earnings',pageMoney.format(Math.max(0,goal-current-deposits)))] }},
  percent:{form:()=>selectField('mode','Calculation',[['of','What is X% of Y?'],['change','Percentage change'],['ratio','X is what percent of Y?']],true)+field('first','First value','20')+field('second','Second value','150')+button('Calculate percentage'),calculate(form){const a=value(form,'first'),b=value(form,'second'),mode=form.elements.mode.value;let result,details;if(mode==='of'){result=a/100*b;details=row(`${a}% of ${pageNumber.format(b)}`,pageNumber.format(result))}else if(mode==='change'){if(a===0)throw Error();result=(b-a)/Math.abs(a)*100;details=row('Starting value',pageNumber.format(a))+row('Ending value',pageNumber.format(b))+row('Direction',result>=0?'Increase':'Decrease')}else{if(b===0)throw Error();result=a/b*100;details=row('Part',pageNumber.format(a))+row('Whole',pageNumber.format(b))}return[pageNumber.format(result)+(mode==='of'?'':'%'),details]}},
  tip:{form:()=>field('bill','Bill amount','84.50',{prefix:'$',step:'0.01',min:0})+field('tip','Tip','20',{suffix:'%',step:'1',min:0})+field('people','Number of people','3',{min:1,step:'1'})+button('Split bill'),calculate(form){const bill=value(form,'bill'),rate=value(form,'tip')/100,people=Math.floor(value(form,'people'));if(bill<0||rate<0||people<1)throw Error();const tip=bill*rate,total=bill+tip;return[pageMoney.format(total/people)+' each',row('Tip amount',pageMoney.format(tip))+row('Total bill',pageMoney.format(total))+row('Party size',people+' people')] }},
  date:{form:()=>field('start','Start date',new Date().toISOString().slice(0,10),{type:'date'})+field('end','End date',new Date(Date.now()+7*86400000).toISOString().slice(0,10),{type:'date'})+button('Count days'),calculate(form){const start=new Date(form.elements.start.value+'T00:00:00Z'),end=new Date(form.elements.end.value+'T00:00:00Z');if(isNaN(start)||isNaN(end))throw Error();const days=Math.round(Math.abs(end-start)/86400000),weeks=Math.floor(days/7);return[pageNumber.format(days)+' days',row('In weeks',pageNumber.format(days/7)+' weeks')+row('Calendar span',weeks+' weeks, '+days%7+' days')+row('Order',end>=start?'Forward in time':'Dates reversed')] }},
  convert:{form:()=>selectField('category','Measurement',[['length','Length'],['mass','Weight / mass'],['temperature','Temperature'],['area','Area'],['volume','Volume'],['speed','Speed']],true)+field('amount','Value','1',{step:'any'})+selectField('from','From',[['m','Meters']])+selectField('to','To',[['ft','Feet']])+button('Convert'),setup(form){const refresh=()=>{const set=units[form.elements.category.value],options=set.items.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');form.elements.from.innerHTML=options;form.elements.to.innerHTML=options;form.elements.to.selectedIndex=Math.min(1,set.items.length-1)};form.elements.category.addEventListener('change',refresh);refresh()},calculate(form){const category=form.elements.category.value,amount=value(form,'amount'),from=form.elements.from.value,to=form.elements.to.value;if(!Number.isFinite(amount))throw Error();let result;if(category==='temperature')result=from==='c'?(to==='f'?amount*9/5+32:to==='k'?amount+273.15:amount):from==='f'?(to==='c'?(amount-32)*5/9:to==='k'?(amount-32)*5/9+273.15:amount):(to==='c'?amount-273.15:to==='f'?(amount-273.15)*9/5+32:amount);else result=amount*units[category].factors[from]/units[category].factors[to];return[pageNumber.format(result)+' '+form.elements.to.selectedOptions[0].text,row('Original',pageNumber.format(amount)+' '+form.elements.from.selectedOptions[0].text)+row('Conversion factor',pageNumber.format(amount===0?0:result/amount))]}},
  bmi:{form:()=>selectField('system','Measurement system',[['us','US (inches, pounds)'],['metric','Metric (centimeters, kilograms)']],true)+field('height','Height','68',{suffix:'in',step:'0.1',min:1})+field('weight','Weight','160',{suffix:'lb',step:'0.1',min:1})+button('Calculate BMI'),setup(form){form.elements.system.addEventListener('change',()=>{const metric=form.elements.system.value==='metric';form.elements.height.value=metric?'173':'68';form.elements.weight.value=metric?'73':'160';form.elements.height.nextElementSibling.textContent=metric?'cm':'in';form.elements.weight.nextElementSibling.textContent=metric?'kg':'lb'})},calculate(form){const h=value(form,'height'),w=value(form,'weight'),metric=form.elements.system.value==='metric';if(h<=0||w<=0)throw Error();const result=metric?w/Math.pow(h/100,2):703*w/Math.pow(h,2),category=result<18.5?'Below standard range':result<25?'Standard range':result<30?'Above standard range':'High range';return[pageNumber.format(result),row('Category',category)+row('Standard reference','18.5 – 24.9')]} }
};

const form=byId('calculatorForm'),tool=tools[document.body.dataset.tool];
form.innerHTML=tool.form();
if(tool.setup)tool.setup(form);
form.addEventListener('submit',event=>{event.preventDefault();try{const [answer,details]=tool.calculate(form);byId('answerValue').textContent=answer;byId('answerDetails').innerHTML=details;byId('toolResult').hidden=false}catch(error){byId('answerValue').textContent='Check your entries';byId('answerDetails').innerHTML=row('Status','Use valid values in every field');byId('toolResult').hidden=false}});
byId('year').textContent=new Date().getFullYear();
